services:
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_tracker
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Menghubungkan seluruh folder project (termasuk mlruns dan mlflow.db) ke /app di kontainer
    working_dir: /app
    command: >
      mlflow server 
      --host 0.0.0.0 doc
      --port 5000 
      --backend-store-uri sqlite:///mlflow.db 
      --default-artifact-root /app/mlruns
    networks:
      - mlops-network

  api-service:
    build: .
    container_name: btc_prediction_api
    ports:
      - "5001:5001"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
      - MLFLOW_TRACKING_INSECURE_TLS=true  # Tambahkan ini
    depends_on:
      - mlflow-server
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge