services:
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_tracker
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    working_dir: /app
    command: >
      mlflow server 
      --host 0.0.0.0 
      --port 5000 
      --backend-store-uri sqlite:///mlruns/mlflow.db 
      --default-artifact-root /app/mlruns
    networks:
      - mlops-network

  api-service:
    build: .
    container_name: btc_prediction_api
    ports:
      - "8000:5001"
    volumes:
      - ./mlruns:/app/mlruns  # PENTING: Agar API bisa membaca file model biner (.pkl)
    working_dir: /app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
      - MLFLOW_TRACKING_INSECURE_TLS=true
      # PENTING: Kosongkan semua proxy bawaan Codespaces agar komunikasi internal antar-container lancar
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - http_proxy=
      - https_proxy=
      - NO_PROXY=mlflow-server,localhost,127.0.0.1
      - no_proxy=mlflow-server,localhost,127.0.0.1
    depends_on:
      - mlflow-server
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge