version: '3.8'

services:
  # LK-10: Layanan Model API MLflow dengan 3 Replika
  model-service:
    image: btc-api-image:latest
    ports:
      - "8080" # Memetakan port internal MLflow (8080) ke port lokal (5001)
    deploy:
      replicas: 3 # MANDAT MUTAK LK-10: 3 INSTANSI BERJALAN BERSAMAAN
    environment:
      - GUNICORN_CMD_ARGS=--timeout 60
    networks:
      - mlops-network

  # LK-11: Kontainer Scraping Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: mlops-binance-klines-prediction-prometheus-1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # LK-11: Kontainer Visualisasi Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge