events { 
    worker_connections 1024; 
}

http {
    # Mendefinisikan grup server replika kita
    upstream model_api_cluster {
        # Docker DNS otomatis mendeteksi 3 replika dari nama service ini
        server model-serving-api:8080;
    }

    server {
        listen 80; # Nginx berjaga di port 80

        location / {
            # Semua request yang masuk ke Nginx dilempar ke grup replika
            proxy_pass http://model_api_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}