name: Continuous Training (CT) Pipeline - LK12

on:
  workflow_dispatch: # 👈 Biar tombol manual di web tetep ada
  repository_dispatch: # 👈 INI KUNCI SAKTI YANG HILANG BIAR WEBHOOK GRAFANA BISA MASUK!
    types: [model_decay_trigger]

jobs:
  retraining-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ingest Fresh Data From Binance API
      run: |
        python src/ingest_data.py  # 👈 GANTI LANGKAH DVC JADI INI (Biar dia bikin data/raw sendiri)
        python src/preprocess.py

    - name: Execute Model Retraining
      run: |
        rm -f mlflow.db
        python src/train.py

    - name: Run Comparative Evaluation
      run: |
        python src/auto_eval_registry.py